[build.environment]
NPM_FLAGS = "--version"
NODE_VERSION = "18"

[build]
publish = "docs/.vitepress/dist"
command = "npx pnpm i && npm run docs:build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
